# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 61356e126360c0a4e01601454c6aa2d7938fe16af2bc2ae14fa91429b3e73f2b04307091222845c42d895498a3ee2d344a7e4e9fe09f0b5831997e2e47b2a2ad

test:
  secret_key_base: 1e91c09088f0945f265794b73767facee55271735bf10198b4cf2f3f0c2724cbec9bf0334223ada182953e94db7c62955cd7e7f3cdecaa060a980ee8785ec038

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
